import tkinter as tk
from tkinter import ttk

class BiomassPowerPlantApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Biomass Power Plant Simulator")

        self.biomass_input_rate = tk.DoubleVar()
        self.power_output = tk.DoubleVar()
        self.steam_production_rate = tk.DoubleVar()

        input_frame = ttk.Frame(self.root)
        input_frame.pack(padx=10, pady=10)

        ttk.Label(input_frame, text="Biomass Input Rate (kg/hour):").grid(row=0, column=0, sticky="w")
        self.input_entry = ttk.Entry(input_frame, textvariable=self.biomass_input_rate)
        self.input_entry.grid(row=0, column=1, padx=5, pady=5)

        self.calculate_button = ttk.Button(input_frame, text="Calculate", command=self.calculate)
        self.calculate_button.grid(row=1, columnspan=2, pady=10)

        output_frame = ttk.Frame(self.root)
        output_frame.pack(padx=10, pady=10)

        ttk.Label(output_frame, text="Power Output (kW):").grid(row=0, column=0, sticky="w")
        self.power_output_label = ttk.Label(output_frame, textvariable=self.power_output)
        self.power_output_label.grid(row=0, column=1, padx=5, pady=5)

        ttk.Label(output_frame, text="Steam Production Rate (kg/hour):").grid(row=1, column=0, sticky="w")
        self.steam_production_label = ttk.Label(output_frame, textvariable=self.steam_production_rate)
        self.steam_production_label.grid(row=1, column=1, padx=5, pady=5)

    def calculate(self):
        biomass_input_rate = self.biomass_input_rate.get()

        # Biomass properties (can be adjusted as needed)
        biomass_moisture_content = 0.1  # Example moisture content (%)
        biomass_lower_heating_value = 18000  # Example lower heating value (kJ/kg)

        # Boiler efficiency (can be adjusted as needed)
        boiler_efficiency = 0.80

        # Turbine efficiency (can be adjusted as needed)
        turbine_efficiency = 0.85

        # Generator efficiency (can be adjusted as needed)
        generator_efficiency = 0.90

        # Calculate the energy content of the biomass input
        biomass_energy_content = biomass_input_rate * (1 - biomass_moisture_content) * biomass_lower_heating_value

        # Calculate the steam production rate
        steam_production_rate = biomass_energy_content / (2260 * 100)  # Assuming enthalpy of vaporization of water is 2260 kJ/kg

        # Calculate the power output of the turbine
        turbine_power_output = steam_production_rate * turbine_efficiency

        # Calculate the electricity generated by the generator
        electricity_generated = turbine_power_output * generator_efficiency

        # Update the labels with the calculated values
        self.power_output.set(round(electricity_generated, 2))
        self.steam_production_rate.set(round(steam_production_rate, 2))

def main():
    root = tk.Tk()
    app = BiomassPowerPlantApp(root)
    root.mainloop()

if __name__ == "__main__":
    main()
